# Generated by Django 3.0.2 on 2020-01-15 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=64)),
                ('backupName', models.CharField(max_length=256)),
                ('eventdatetime', models.DateTimeField()),
                ('resultCode', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionName', models.CharField(max_length=64)),
                ('regionCode', models.IntegerField()),
                ('regionDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceWSDLURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Services')),
            ],
        ),
        migrations.CreateModel(
            name='GetVersionXML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml', models.TextField()),
                ('rervice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Services')),
            ],
        ),
    ]
