# Generated by Django 3.0.2 on 2020-01-15 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_backupstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getversionxml',
            old_name='rervice',
            new_name='service',
        ),
    ]
