# Generated by Django 3.0.2 on 2020-01-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200115_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regions',
            old_name='regionName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='serviceName',
            new_name='name',
        ),
    ]
