# Generated by Django 3.0.2 on 2020-01-15 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionName', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='BackupNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backupName', models.CharField(max_length=256)),
                ('eventdatetime', models.DateTimeField()),
                ('success', models.BooleanField()),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backupnotification.Regions')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backupnotification.Services')),
            ],
        ),
    ]
