# Generated by Django 3.0.2 on 2020-01-21 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('ip', models.GenericIPAddressField()),
            ],
            options={
                'unique_together': {('name', 'ip')},
            },
        ),
        migrations.CreateModel(
            name='BackupNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('size', models.IntegerField()),
                ('eventdatetime', models.DateTimeField()),
                ('success', models.BooleanField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backupnotification.Host')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backupnotification.Region')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backupnotification.Service')),
            ],
        ),
    ]
