# Generated by Django 3.0.2 on 2020-01-15 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backupnotification', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Regions',
            new_name='Region',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
